### ISSUE TITLE
UpdateRecurringPaymentsProfile throws error

### ISSUE THREAD

**Issue by vimalnath53** [paypal/merchant-sdk-dotnet#23]
When I try to run the UpdateRecurringPaymentsProfile.aspx,
it results in "PayPal.Exception.HttpException was unhandled by user code".
Here are the complete logs:

**PayPal.Exception.HttpException** was unhandled by user code
**HResult**=-2146233088
**Message**=The remote server returned an error: (500) Internal Server Error.
**Source**=PayPalCoreSDK
**Response**=
````xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cc="urn:ebay:apis:CoreComponentTypes" xmlns:wsu="http://schemas.xmlsoap.org/ws/2002/07/utility" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ebl="urn:ebay:apis:eBLBaseComponents" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:ns="urn:ebay:api:PayPalAPI">
    <SOAP-ENV:Header>
        <Security xmlns="http://schemas.xmlsoap.org/ws/2002/12/secext" xsi:type="wsse:SecurityType"/>
        <RequesterCredentials xmlns="urn:ebay:api:PayPalAPI" xsi:type="ebl:CustomSecurityHeaderType">
            <Credentials xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:UserIdPasswordType">
                <Username xsi:type="xs:string">xxx</Username>
                <Password xsi:type="xs:string">xxx</Password>
                <Signature xsi:type="xs:string">xxx</Signature>
                <Subject xsi:type="xs:string"/>
            </Credentials>
        </RequesterCredentials>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body id="_0">
        <SOAP-ENV:Fault>
            <faultcode>SOAP-ENV:Client</faultcode>
            <faultstring>Timeout processing request</faultstring>
        </SOAP-ENV:Fault>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
````
**StackTrace:**
````
at PayPal.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
at PayPal.APIService.MakeRequestUsing(IAPICallPreHandler apiCallHandler)
at PayPal.BasePayPalService.Call(IAPICallPreHandler apiCallHandler)
at PayPal.PayPalAPIInterfaceService.PayPalAPIInterfaceServiceService.UpdateRecurringPaymentsProfile(UpdateRecurringPaymentsProfileReq updateRecurringPaymentsProfileReq, String apiUserName)
at PayPal.PayPalAPIInterfaceService.PayPalAPIInterfaceServiceService.UpdateRecurringPaymentsProfile(UpdateRecurringPaymentsProfileReq updateRecurringPaymentsProfileReq)
at PayPalAPISample.APICalls.UpdateRecurringPaymentsProfile.Submit_Click(Object sender, EventArgs e) in c:\csharp\merchant-sdk-dotnet-master\Samples\PayPalAPISample\APICalls\UpdateRecurringPaymentsProfile.aspx.cs:line 40
at System.Web.UI.HtmlControls.HtmlInputButton.OnServerClick(EventArgs e)
at System.Web.UI.HtmlControls.HtmlInputButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.HtmlControls.HtmlInputButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
InnerException:
````

**Comment by jziaja** [comment]
Hi @vimalnath53, is this error happening repeatedly?  Also, could you post the full body of the error response?  Thanks!

**Comment by jziaja** [comment]
@vimalnath53 , can you share the **recurring profile ID** you're trying to update along with the **date and time (including timezone)** the request was sent?  Thanks!

**Comment by juwlee** [comment]
@vimalnath53 along with what @jziaja requested, could you also share the response header?

**Comment by jziaja** [comment]
This issue is being tracked internally with ticket #PPPLBUS-7523.

**Comment by jziaja** [comment]
Issue was caused by the `SubscriberName` field in the profile being empty.  The sample code needs to be updated to set this field.
