### ISSUE TITLE
Could not load file or assembly 'PayPalCoreSDK, Version=1.6.1.0

### ISSUE THREAD

**Issue by faheemsial** [paypal/merchant-sdk-dotnet#40]
Project has PayPalCoreSDK.DLL version 1.7.1 but While running sample project i am getting error below:

Error Caught in Application_Error event
Error in: http://localhost:3035/ShowError.aspx?aspxerrorpath=/APICalls/CreateRecurringPaymentsProfile.aspx

Error Message:Could not load file or assembly 'PayPalCoreSDK, Version=1.6.1.0, Culture=neutral, PublicKeyToken=5b4afc1ccaef40fb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Stack Trace:   at PayPalAPISample.APICalls.CreateRecurringPaymentsProfile.Submit_Click(Object sender, EventArgs e)
   at System.Web.UI.HtmlControls.HtmlInputButton.OnServerClick(EventArgs e)
   at System.Web.UI.HtmlControls.HtmlInputButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.HtmlControls.HtmlInputButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by faheemsial** [comment]
I was trying to CreateRecurringPaymentsProfile and getting above error on submit.

**Comment by CEngen1** [comment]
Same issue for me.  I was trying to use GetTransactionDetails....  

I tried unloading project and checking the .proj file, reloading the project, wiping out bin, and obj directories, exiting visual studio and loading it all back up again, cleaning and rebuilding, dropping the references and reloading them (3 PayPalCoreSDK, PayPalMerchantSDK, and PayPalPermissionsSDK)

no understanding where it thinks I have a version 1.6.1.0 .... everything I can find is 1.7.0.0.

Here's my info:

Error Caught in Application_Error event
Error in: http://localhost:3035/ShowError.aspx?aspxerrorpath=/APICalls/GetTransactionDetails.aspx

Error Message:Could not load file or assembly 'PayPalCoreSDK, Version=1.6.1.0, Culture=neutral, PublicKeyToken=5b4afc1ccaef40fb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Stack Trace:   at PayPalAPISample.APICalls.GetTransactionDetails.Search_Submit(Object sender, EventArgs e)
   at System.Web.UI.HtmlControls.HtmlInputButton.OnServerClick(EventArgs e)
   at System.Web.UI.HtmlControls.HtmlInputButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.HtmlControls.HtmlInputButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by CEngen1** [comment]
I resolved my issue, by using nuget manager in Visual Studio and getting an update.  Still never understood what could be saying version 1.6.1.0

**Comment by sudheerZbross** [comment]
is there any update for above question ,,,,i m getting same issue message when accessing getBalance page

**Comment by faheemsial** [comment]
No dear there wasn't any update from paypal, but i figured out issue as there DLL file was internally referencing old NewtonSoft.JSON (i think 7.0) causing this exception. I switched my solution from paypal sdk to Braintree (PayPal) and rewrite my code using Braintree.dll and it is working fine.
